### ISSUE TITLE
Debugowanie - błąd

### ISSUE THREAD

**Issue by jakubg1** [jakubg1/Generator-wpis-w-do-semafor-w-Train-Driver-2-Semaphore-code-generator-for-Train-Driver-2#2]
Debugowanie zawiera błąd z konwertowaniem liczby na tekst. Będzie poprawione w następnej wersji.

**Comment by l0stfake7** [comment]
Debugowanie poprawione, aczkolwiek to mało uniwersalne rozwiązanie, pomimo tego powinno na razie wystarczyć.

**Comment by jakubg1** [comment]
Dodałem resztę informacji o debugowaniu. Okazało się, że niektóre zmienne nie działają, aczkolwiek zajmę się tym jak już dokończę okno. Samo debugowanie działa bez zarzutu, więc uznaję za ukończone. W miarę dokańczania zmiennych debugowanie będzie uzupełniane.
