### ISSUE TITLE
Samozaznaczenie wybranej opcji w Combo Boxie

### ISSUE THREAD

**Issue by jakubg1** [jakubg1/Generator-wpis-w-do-semafor-w-Train-Driver-2-Semaphore-code-generator-for-Train-Driver-2#5]
@l0stfake7, wiesz może jak to zrobić?

**Comment by l0stfake7** [comment]
Nie do końca rozumiem co ma być samoistnie zaznaczane i w którym momencie, chodzi o jakieś domyślne zaznaczenie?
Sprawdź najnowszy commit(26) i napisz czy tak miało być.

**Comment by jakubg1** [comment]
Nie, chodziło mi o to że po naciśnięciu "Konfiguruj" ustawi się odpowiednie komory.
Ale nie usuwaj tych zmian co wtedy zrobiłeś. ;)

**Comment by nitro2010-zz** [comment]
Możesz np. użyć ustawienia poprzez selekcję na podstawie nr indeksu, np.

`  TextBoxKomora4.SelectedIndex = 2;`

Oznacza, że ustawi 3 pozycję na liście rozwijalnej.

Pamiętaj też, że wszelakie tablice, listy, itd. liczymy od indeksu 0, a nie 1, więc jeżeli będziesz chciał np. wybrać kolor czerwony z listy to licząc jest on na 6 pozycji, ale poprzez wybór indeksu jest na 5 pozycji.

**Comment by jakubg1** [comment]
Tak naprawdę problem już dawno stał się nieaktualny - odkąd _l0stfake7 zaczął przepisywać okno na język wpf.
